<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
	<LangVersion>preview</LangVersion>
	<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	<PublishAot>False</PublishAot>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.1" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
    <PackageReference Include="Avalonia.Wayland" Version="12.1.1" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.1" />
    <PackageReference Include="Xaml.Behaviors" Version="12.0.5" />
    <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="4.13.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.1" />
	<PackageReference Include="ReactiveUI" Version="20.1.63" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EngineLib\EngineLib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\EditorWindow.axaml.cs">
      <DependentUpon>EditorWindow.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\FilterWindow.axaml.cs">
      <DependentUpon>FilterWindow.axaml</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>